### ISSUE TITLE
When I edit a field, the publish changes button doesn't appear

### ISSUE THREAD

**Issue by mhwlng** [episerver/EPiServer.Labs.BlockEnhancements#24]
When I edit a field, the `publish changes` button doesn't appear.
![image](https://user-images.githubusercontent.com/1388886/66730818-3a0b6680-ee54-11e9-9f4a-497647f02488.png)
I press OK, now I see the pencil icon.
Then I open the form again, now I can see the publish changes button :
![image](https://user-images.githubusercontent.com/1388886/66730824-442d6500-ee54-11e9-8c13-1c0c797f5bd1.png)

**Comment by barteksekula** [comment]
This is by design. When you open the form for the first time, you are actually seeing a published version, no draft is available at this point. We do not have custom code to calculate if the access rights of the current user are sufficient to publish stuff so we use the Core api. So basically we would show the button only when such button would also be available if you opened this block instance in a standard way (by clicking View in the Content Area).
I like your idea because it would simplify a lot (for example we could also think about completely removing 'Save' for local blocks etc..) but it's quite a big enhancement, not a bug that we will fix anytime soon.
