### ISSUE TITLE
Unable to move inline-editing modal dialog

### ISSUE THREAD

**Issue by tednyberg** [episerver/EPiServer.Labs.BlockEnhancements#36]
**Expected behavior:**
When inline-editing dialog is displayed, I expect to be able to click-and-drag to move it to see what's behind.

**Actual behavior:**
Dialog is fixed in place, nothing happens when I click and drag it. No errors in console. It happens in both "All properties" and "On-page editing" mode.

**Screencast:**
https://screencast-o-matic.com/watch/cqlFiLvQzH

**Comment by barteksekula** [comment]
@tednyberg Due to dojo's DialogBase issues with positioning we had to hardcode the position:
https://github.com/episerver/EPiServer.Labs.BlockEnhancements/blob/master/src/alloy/modules/_protected/episerver-labs-block-enhancements/1.0.0/Scripts/inline-editing/inline-edit.css#L3-L5

Maybe you would like to give it a shot? ; )

**Comment by tednyberg** [comment]
> Due to dojo's DialogBase issues with positioning we had to hardcode the position:

Ah, I see - I'll try and make time for finding a fix/workaround. Fingers crossed! :)
