### ISSUE TITLE
Disable glass effect to allow media etc to be drag-and-dropped to dialog

### ISSUE THREAD

**Issue by tednyberg** [episerver/EPiServer.Labs.BlockEnhancements#52]
I think the glass overlay is new? It blocks you from dragging-and-dropping media etc to the dialog.

For example, in this example I'd like to be able to drag-and-drop images from the "Media" tab to the image property of the block being edited:

![image](https://user-images.githubusercontent.com/3976064/77161123-3508ae00-6aa9-11ea-8a1e-6d09353076b5.png)

**Comment by barteksekula** [comment]
@tednyberg No, unfortunately it's been like this since the beginning.
In order to workaround this we added 
https://github.com/episerver/EPiServer.Labs.BlockEnhancements#inline-create
and 
https://github.com/episerver/EPiServer.Labs.BlockEnhancements#configuring-enabled-features
**ContentAreaBrowse**

But that works only for ContentArea. In case for your custom property editor I'm afraid you would have to try to reuse our modules and also display a link like 'Add new image' or something.
D&D won't work because we cannot risk two FormContainer instances to be "active" at the same time, maybe in the future we will get away from the dialog.

**Comment by barteksekula** [comment]
This is now part of CMS UI https://nuget.episerver.com/package/?id=EPiServer.CMS.UI&v=11.34.0
