### ISSUE TITLE
ContentAreaDescriptor with OverrideDefault

### ISSUE THREAD

**Issue by benklaw** [episerver/EPiServer.Labs.BlockEnhancements#60]
Hi,
I've noticed that the ContentAreaDescriptor uses EditorDescriptorBehavior.OverrideDefault which basically closes down the default registration for the ContentArea as the MetadataHandlerRegistry only accepts one OverrideDefault registration.

Would it be possible to configure how the ContentAreaDescriptor is registered by the plugin? We are overriding the default registration our self to add functionality and right now both registrations collide. Whoever gets registered first wins.

In a perfect world I guess it would be great if it would be possible to extend the default editor descriptor. EditorDescriptorBehavior.ExtendBase unfortunately only works with ui hints. But I guess changes to the MetadataHandlerRegistry are out of your control.

**Comment by barteksekula** [comment]
@benklaw Changing MetadataHandlerRegistry is not an option for now unfortunately.
The best I can think of now is to expose a new prop of type `EditorDescriptorBehavior` in `BlockEnhancementsOptions` class.
The default value would be EditorDescriptorBehavior.OverrideDefault.
However, it would be possible for you to change that so that your own implementation with OverrideDefault wins.
Maybe even your implementation could inherit from `EPiServer.Labs.BlockEnhancements.InlineBlocksEditing.ContentAreaDescriptor` in order to get custom client editing classes?
Please let me know what you think, I have some time today.

**Comment by benklaw** [comment]
@barteksekula I think having the `EditorDescriptorBehavior ` configurable in the `BlockEnhancementsOptions` would definitely help. Maybe also with an optional UIHint. 
I'm trying to keep to usage of the plugin optional in our projects while I'm still evaluating it. So I wouldn't inherit from your ContentAreaDescriptor right now. But it would be an option later on.

**Comment by barteksekula** [comment]
This will be available in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.9.3 which is due to be released next week.
