### ISSUE TITLE
Not able to edit block when every config is set to true

### ISSUE THREAD

**Issue by LimaPer** [episerver/EPiServer.Labs.BlockEnhancements#84]
Running on latest Episerver 11(on premise) (Episerver: 11.20.9.0, UI: 11.36.3.0, Forms.UI: 4.30.4.0, BlockEnhancement: 0.11.0.0) we noticed with every config set to true its not possible to edit some of the blocks. The actual edit menu is replaced with quick edit (even if its called edit). 

Due to this we are not able to reach all the functions for a Form container (for example control email settings after a form post) and the Selection Form item only opens with base functionality so its not possible to add any choices. 

The For this page is also hidden so cant reach the block backend with that functionality. 

Like the functionality of the BlockEnhancement but had to set the following configs to false to get it to work. 
LocalContentFeatureEnabled
HideForThisFolder
InlineTranslate (not sure that this one matters but had to solve it quickly for the client and was an irrelevant function)

We had this issue in two different live environments. It was possible to fix with config changes but assume its not a desired functionality described above that you cant edit all the properties of a block.

**Comment by barteksekula** [comment]
The idea behind this was to tie the lifetime of the page with its local blocks.
Introduced here: https://world.optimizely.com/blogs/bartosz-sekula/dates/2021/9/block-enhancements-update/ in v0.11.0
It seems we haven't fully tested with the Forms add-on.
I will take a look.

**Comment by barteksekula** [comment]
Fixed in https://nuget.optimizely.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.12.0
You can now control on which content types you want regular Edit or Quick Edit (Forms are using regular Edit by default).
You can also decide if you want to see the `For this page` blocks folder or not. 
Or you can also decide to turn on Quick Edit for shared content (off by default).
https://github.com/episerver/EPiServer.Labs.BlockEnhancements#blockenhancementsoptions
